app/caveapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("database.urls", "db")),
    path("grappelli/", include("grappelli.urls")),
    path("admin/", admin.site.urls),
]

app/core/urls.py
from django.urls import path

from . import views

urlpatterns = []

app/database/urls.py
from django.urls import path

from . import views

app_name = "db"

urlpatterns = [
    path("", views.index, name="index"),
    path("region/<slug:slug>", views.region, name="region"),
    path("cave/<slug:slug>", views.cave, name="cave"),
    path("system/<slug:slug>", views.system, name="system"),
    path("country/<slug:slug>", views.country, name="country"),
    path("search/", views.search, name="search"),
]

app/core/models.py
from django.db import models

# Create your models here.

app/database/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError


class Country(models.Model):
    class Meta:
        verbose_name_plural = "countries"

    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)
    country = models.ForeignKey(
        "Country",
        on_delete=models.PROTECT,
    )
    website = models.URLField(blank=True, null=True)
    wikipedia = models.URLField(blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.name} ({self.country})"


class GenericOrganisation(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=50, unique=True)
    abbreviation = models.CharField(max_length=10)
    slug = models.SlugField(unique=True)
    country = models.ForeignKey(
        "Country",
        on_delete=models.PROTECT,
    )
    region = models.ForeignKey(
        "Region",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    website = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def clean(self):
        """Validate that the selected Region is part of the selected Country"""
        if self.region:
            if not self.region.country == self.country:
                raise ValidationError(
                    {"region": "The region must be part of the selected country."},
                    code="invalid",
                )


class Organisation(GenericOrganisation):
    pass


class Club(GenericOrganisation):
    location = models.CharField(max_length=50)


class GenericCave(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    region = models.ForeignKey(
        "Region",
        on_delete=models.PROTECT,
    )
    location = models.CharField(max_length=50)
    latitude = models.DecimalField(
        max_digits=9, decimal_places=6, blank=True, null=True
    )
    longitude = models.DecimalField(
        max_digits=9, decimal_places=6, blank=True, null=True
    )
    length = models.DecimalField(
        verbose_name="length in kilometres",
        blank=True,
        null=True,
        decimal_places=3,
        max_digits=6,
    )
    depth = models.IntegerField(verbose_name="depth in metres", blank=True, null=True)
    wikipedia = models.URLField(blank=True, null=True)
    organisation = models.ForeignKey(
        "Organisation",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    website = models.URLField(blank=True, null=True)
    resources = models.TextField(blank=True)
    references = models.TextField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def country(self):
        return self.region.country


class CaveSystem(GenericCave):
    def number_of_caves(self):
        return len(self.cave_set.all())

    def url(self):
        return reverse("db:system", kwargs={"slug": self.slug})

    def type(self):
        return "System"


class Cave(GenericCave):
    system = models.ForeignKey(
        "CaveSystem",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )

    def url(self):
        return reverse("db:cave", kwargs={"slug": self.slug})

    def type(self):
        return "Cave"

app/core/views.py
from django.shortcuts import render

app/database/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.db.models import Q
from queryset_sequence import QuerySetSequence
from .models import Region, Cave, CaveSystem, Country


def index(request):
    query = QuerySetSequence(Cave.objects.all(), CaveSystem.objects.all())
    recent_updates = query.order_by("updated_on")[:10].select_related(
        "region",
        "region__country",
    )
    regions = (
        Region.objects.all()
        .select_related(
            "country",
        )
        .prefetch_related(
            "cavesystem_set",
            "cave_set",
        )
    )

    context = {
        "recent": recent_updates,
        "regions": regions,
    }
    return render(request, "dbindex.html", context)


def region(request, slug):
    region = get_object_or_404(Region, slug=slug)
    caves = region.cave_set.all().select_related(
        "organisation",
        "system",
    )
    systems = (
        region.cavesystem_set.all()
        .select_related(
            "organisation",
        )
        .prefetch_related(
            "cave_set",
        )
    )

    context = {
        "region": region,
        "caves": caves,
        "systems": systems,
    }
    return render(request, "region.html", context)


def cave(request, slug):
    context = {
        "cave": get_object_or_404(Cave, slug=slug),
        "type": "cave",
    }
    return render(request, "cave.html", context)


def system(request, slug):
    cave = get_object_or_404(CaveSystem, slug=slug)
    subcaves = cave.cave_set.all().select_related("region")

    context = {
        "cave": cave,
        "caves_in_system": subcaves,
        "type": "system",
    }
    return render(request, "cave.html", context)


def country(request, slug):
    country = get_object_or_404(Country, slug=slug)

    systems = CaveSystem.objects.none()
    caves = Cave.objects.none()
    for region in country.region_set.all():
        caves = caves.union(
            region.cave_set.all().select_related(
                "organisation",
                "region",
                "system",
            )
        )

        systems = systems.union(
            region.cavesystem_set.all()
            .select_related(
                "organisation",
                "region",
            )
            .prefetch_related("cave_set")
        )

    context = {
        "country": country,
        "systems": systems,
        "caves": caves,
    }

    if len(context["caves"]) == 0 and len(context["systems"]) == 0:
        context["no_caves"] = True

    return render(request, "country.html", context)


def search(request):
    if not "terms" in request.GET:
        raise Http404("Search page accessed with no terms specified")

    search_terms = request.GET["terms"].strip()

    # Only allow sensible searches
    if len(search_terms) < 3:
        if len(search_terms) == 0:
            error_msg = "You must enter some search terms. Please try again."
        else:
            error_msg = "You must enter at least three characters into the search box. Please try again."

        context = {
            "terms": search_terms,
            "results": None,
            "number_of_results": 0,
            "error": error_msg,
        }
        return render(request, "search.html", context)

    # Build the results
    query = QuerySetSequence(Cave.objects.all(), CaveSystem.objects.all())
    # Search name and location
    st = search_terms
    results = query.filter(Q(name__icontains=st) | Q(location__iexact=st))
    results = results.select_related(
        "organisation",
        "region",
        "region__country",
    )

    # If only one result, and it's a Cave or CaveSystem, just redirect to the page
    if len(results) == 1:
        result = results[0]
        if result.__class__ == CaveSystem:
            return redirect("db:system", slug=result.slug)
        elif result.__class__ == Cave:
            return redirect("db:cave", slug=result.slug)

    context = {
        "terms": search_terms,
        "results": results,
        "number_of_results": len(results),
    }
    return render(request, "search.html", context)

app/database/templates/cave.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load gmaps_extras %}
{% block title %}{{ cave.name }} - {{ cave.region }}{% endblock %}
{% block description %}Details on the length and depth of {{ cave.name }} beneath {{ cave.location }} in {{ cave.region }}.{% endblock %}
{% block content %}

<h1 class="mb-0 display-4"><span class="text-muted">{{ type|capfirst }}:</span> {{ cave.name }}</h1>

<!-- Breadcrumbs start -->
<span class="fw-light mt-0 text-muted">
  <a href="{% url 'db:country' cave.country.slug %}" class="text-muted">{{ cave.country }}</a>
  &rarr; <a href="{% url 'db:region' cave.region.slug %}" class="text-muted">{{ cave.region.name }}</a>
  &rarr; <a href="{% url 'db:search' %}?terms={{ cave.location|urlencode }}" class="text-muted">{{ cave.location }}</a>

  {% if type == "cave" and cave.system %}
  &rarr; <a href="{% url 'db:system' cave.system.slug %}" class="text-muted">{{ cave.system.name }}</a>
  {% endif %}
</span>
<!-- Breadcrumbs end -->

<br /><br />

<!-- Description start -->
{% if cave.description %}
{{ cave.description | markdown | safe }}<br />
{% endif %}
<!-- Description end -->

<!-- Datasheet start -->
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr class="table-title text-center">
        <th colspan="2" scope="col">{{ cave.name }} - Datasheet</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <th scope="row">Name</th>
        <td>{{ cave.name }}</td>
      </tr>

      {% if type == "cave" %}

      <tr>
        <th scope="row">Cave system</th>
        {% if cave.system %}
        <td><a class="text-muted" href="{% url 'db:system' cave.system.slug %}">{{ cave.system.name }}</a></td>
        {% else %}
        <td>Not recorded</td>
        {% endif %}
      </tr>

      {% elif type == "system" %}

      <tr>
        <th scope="row">Caves in system</th>
        {% with cave_num=cave.number_of_caves %}
        {% if cave_num > 0 %}
        <td>{{ cave_num }} recorded on CaveDB - see table below</td>
        {% else %}
        <td>None recorded on CaveDB</td>
        {% endif %}
        {% endwith %}
      </tr>

      {% endif %}

      <tr class="table-title text-center">
        <th scope="row" colspan="2">Location</th>
      </tr>

      <tr>
        <th scope="row">Country</th>
        <td><a href="{% url 'db:country' cave.country.slug %}" class="text-muted">{{ cave.country }}</a></td>
      </tr>

      <tr>
        <th scope="row">Region</th>
        <td><a href="{% url 'db:region' cave.region.slug %}" class="text-muted">{{ cave.region.name }}</a></td>
      </tr>

      <tr>
        <th scope="row">Location</th>
        <td><a href="{% url 'db:search' %}?terms={{ cave.location|urlencode }}" class="text-muted">{{ cave.location }}</a></td>
      </tr>

      <tr>
        <th scope="row">{{ type|capfirst }} coordinates</th>
        {% if cave.latitude and cave.longitude %}
        <td>
          {{ cave.latitude }}, {{ cave.longitude }}
          <a class="text-muted" href="{{ cave|gmaps }}"><i class="fa-solid fa-map-location-dot"></i></a>
        </td>
        {% else %}
        <td>Not recorded</td>
        {% endif %}
      </tr>

      <tr class="text-center table-title">
        <th scope="row" colspan="2">Length and Depth</th>
      </tr>

      <tr>
        <th scope="row">Length (km)</th>
        <td>{{ cave.length|default:"Not recorded" }}</td>
      </tr>

      <tr>
        <th scope="row">Depth (m)</th>
        <td>{{ cave.depth|default:"Not recorded" }}</td>
      </tr>

      <tr class="table-title text-center">
        <th scope="row" colspan="2">External Resources</th>
      </tr>

      <tr>
        <th scope="row">Organisation</th>
        <td>
          {{ cave.organisation|default:"Not recorded" }}
          {% if cave.organisation.website %}
          <a class="text-muted" href="{{ cave.organisation.website }}"><i class="fa-solid fa-arrow-up-right-from-square"></i></a>
          {% endif %}
        </td>
      </tr>

      <tr>
        <th scope="row">{{ type|capfirst }} website</th>
        {% if cave.website %}
        <td><a class="text-muted" href="{{ cave.website }}">{{ cave.website }}</a></td>
        {% else %}
        <td>Not recorded</td>
        {% endif %}
      </tr>

      <tr>
        <th scope="row">Wikipedia link</th>
        {% if cave.wikipedia %}
        <td><a class="text-muted" href="{{ cave.wikipedia }}">{{ cave.wikipedia }}</a></td>
        {% else %}
        <td>Not recorded</td>
        {% endif %}
      </tr>

      <tr>
        <th scope="row">Further resources</th>
        <td>{{ cave.resources | markdown | safe | default:"Not recorded"}}</td>
      </tr>

      <tr class="text-center table-title">
        <th scope="row" colspan="2">Database</th>
      </tr>

      <tr>
        <th scope="row">References</th>
        <td>{{ cave.references | markdown | safe | default:"Not recorded"}}</td>
      </tr>

      <tr>
        <th scope="row">Added to database</th>
        <td>{{ cave.added_on | date:"l, jS F Y, H:i e" }}</td>
      </tr>

      <tr>
        <th scope="row">Last updated</th>
        <td>{{ cave.updated_on | date:"l, jS F Y, H:i e" }}</td>
      </tr>

      {% if type == "system" %}
      <!-- Caves in system start -->
      {% if caves_in_system %}
      <tr class="text-center table-title">
        <th scope="row" colspan="2">Caves in System</th>
      </tr>

      {% for subcave in caves_in_system %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>
          <a class="text-muted" href="{% url 'db:cave' subcave.slug %}">{{ subcave.name }}</a>
          <span class="text-muted">({{ subcave.location }} / {{ subcave.region.name }})</span>
        </td>
      </tr>
      {% endfor %}
      {% endif %}
      <!-- Caves in system end -->
      {% endif %}

    </tbody>
  </table>
</div>
<!-- Datasheet end -->

{% endblock %}

app/database/templates/dbindex.html
{% extends "base.html" %}
{% block title %}CaveDB{% endblock %}
{% block description %}An online database of caves and cave systems.{% endblock %}
{% block content %}

<!-- Header start -->
<h1 class="mb-0 display-4 text-center">CaveDB</h1>
<br /><br />
<!-- Header end -->

<!-- Regions table start -->
<div class="table-responsive">
  <table id="regionList" class="table text-center">
    <thead>
      <tr>
        <th scope="col" colspan="5">Caving Regions</th>
      </tr>

      <tr data-sort-method="thead">
        <th scope="col">#</th>
        <th scope="col">Country</th>
        <th scope="col">Region</th>
        <th scope="col" data-sort-method="number">Caves recorded</th>
        <th scope="col" data-sort-method="number">Systems recorded</th>
      </tr>
    </thead>

    <tbody>
      {% for region in regions|dictsort:"country.name" %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'db:country' region.country.slug %}" class="text-muted">{{ region.country }}</a></td>
        <td><a href="{% url 'db:region' region.slug %}" class="text-muted">{{ region.name }}</a></td>
        <td>{{ region.cave_set.all|length }}</td>
        <td>{{ region.cavesystem_set.all|length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<!-- Regions table end -->

<br /><br />

<!-- Recent updates table start -->
<div class="table-responsive">
  <table class="table text-center">
    <thead>
      <tr>
        <th scope="col" colspan="6">Recent Updates</th>
      </tr>

      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Country</th>
        <th scope="col">Region</th>
        <th scope="col">Location</th>
        <th scope="col">Updated</th>
      </tr>
    </thead>

    <tbody>

      {% for update in recent %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{{ update.url }}" class="text-muted">{{ update.name }}</a></td>
        <td><a href="{% url 'db:country' update.region.country.slug %}" class="text-muted">{{ update.region.country }}</a></td>
        <td><a href="{% url 'db:region' update.region.slug %}" class="text-muted">{{ update.region.name }}</a></td>
        <td><a href="{% url 'db:search' %}?terms={{ update.location|urlencode }}" class="text-muted">{{ update.location }}</a></td>
        <td>{{ update.updated_on|timesince }} ago</td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
<!-- Recent updates table end -->


{% endblock %}

{% block footer_scripts %}
<!-- Enable tablesort -->
<script>
  new Tablesort(document.getElementById('regionList'));
</script>
{% endblock %}

app/database/templates/region.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load gmaps_extras %}

{% block title %}Caves in {{ region }}{% endblock %}
{% block description %}A list of caves recorded in {{ region }}.{% endblock %}

{% block content %}
<!-- Header start -->
<h1 class="mb-0 display-4"><span class="text-muted">Region:</span> {{ region.name }}</h1>
<!-- Breadcrumbs start-->
<span class="fw-light mt-0 text-muted">
  <a href="{% url 'db:country' region.country.slug %}" class="text-muted">{{ region.country }}</a>
  &rarr; <a href="{% url 'db:region' region.slug %}" class="text-muted">{{ region.name }}</a>
</span>
<br /><br />
<!-- Breadcrumbs end -->
<!-- Header end -->

{% if not caves and not systems %}
<p class="lead">Sorry, this region currently has no caves or cave systems stored within the database.</p>
{% else %}

<!-- Description start-->
{% if region.description %}
{{ region.description | markdown | safe }}<br />
{% endif %}
<!-- Description end-->

<!-- Datasheet start -->
{% if systems %}
<!-- System list start -->
<div class="table-responsive">
  <table id="systemList" class="table text-center">
    <thead>
      <tr>
        <th scope="col" class="text-center" colspan="9">Cave Systems in {{ region.name }}</th>
      </tr>

      <tr data-sort-method="thead">
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col" data-sort-method="number">Caves</th>
        <th scope="col" data-sort-method="number">Length (km)</th>
        <th scope="col" data-sort-method="number">Depth (m)</th>
        <th scope="col">Organisation</th>
        <th scope="col">Website</th>
        <th scope="col">Wikipedia</th>
      </tr>
    </thead>

    <tbody>

      {% for cave in systems|dictsort:"location" %}
      <tr>

        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-muted" href="{% url 'db:system' cave.slug %}">{{ cave.name }}</a></td>
        <td><a href="{% url 'db:search' %}?terms={{ cave.location|urlencode }}" class="text-muted">{{ cave.location }}</a></td>
        <td>{{ cave.number_of_caves }}</td>
        <td>{{ cave.length|floatformat:"-3"|default:"-" }}</td>
        <td>{{ cave.depth|floatformat:"-3"|default:"-" }}</td>

        {% if cave.organisation.website %}
        <td>{{ cave.organisation.abbreviation }} <a href="{{ cave.organisation.website }}" class="text-muted"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>
        {% else %}
        <td>{{ cave.organisation.abbreviation|default:"-" }}</td>
        {% endif %}

        {% if cave.website %}
        <td><a href="{{ cave.website }}" class="text-muted"><i class="fa-solid fa-link"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

        {% if cave.wikipedia %}
        <td><a href="{{ cave.wikipedia }}" class="text-muted"><i class="fa-brands fa-wikipedia-w"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

      </tr>
      {% endfor %}

    </tbody>
  </table>
</div><br />
<!-- System list end -->
{% endif %}

<!-- Cave list start -->
{% if caves %}
<div class="table-responsive">
  <table id="caveList" class="table text-center">
    <thead>
      <tr>
        <th scope="col" class="text-center" colspan="9">Caves in {{ region.name }}</th>
      </tr>

      <tr data-sort-method="thead">
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col">System</th>
        <th scope="col" data-sort-method="number">Length (km)</th>
        <th scope="col" data-sort-method="number">Depth (m)</th>
        <th scope="col">Organisation</th>
        <th scope="col">Website</th>
        <th scope="col">Wikipedia</th>
      </tr>
    </thead>

    <tbody>

      {% for cave in caves|dictsort:"location" %}
      <tr>

        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-muted" href="{% url 'db:cave' cave.slug %}">{{ cave.name }}</a></td>
        <td><a href="{% url 'db:search' %}?terms={{ cave.location|urlencode }}" class="text-muted">{{ cave.location }}</a></td>

        {% if cave.system %}
        <td><a href="{% url 'db:system' cave.system.slug %}" class="text-muted">{{ cave.system.name }}</a></td>
        {% else %}
        <td>-</td>
        {% endif %}

        <td>{{ cave.length|floatformat:"-3"|default:"-" }}</td>
        <td>{{ cave.depth|floatformat:"-3"|default:"-" }}</td>

        {% if cave.organisation.website %}
        <td>{{ cave.organisation.abbreviation }} <a href="{{ cave.organisation.website }}" class="text-muted"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>
        {% else %}
        <td>{{ cave.organisation.abbreviation|default:"-" }}</td>
        {% endif %}

        {% if cave.website %}
        <td><a href="{{ cave.website }}" class="text-muted"><i class="fa-solid fa-link"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

        {% if cave.wikipedia %}
        <td><a href="{{ cave.wikipedia }}" class="text-muted"><i class="fa-brands fa-wikipedia-w"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
<!-- Cave list end -->
{% endif %}
<!-- Datasheet end -->
{% endif %}

{% endblock %}

{% block footer_scripts %}
{% if caves or systems %}
<!-- Enable tablesort -->
<script>
  {% if caves %}new Tablesort(document.getElementById('caveList'));{% endif %}
  {% if systems %}new Tablesort(document.getElementById('systemList'));{% endif %}
</script>
{% endif %}
{% endblock %}

app/database/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if terms %}
Search for {{ terms }}
{% else %}
CaveDB: Search
{% endif %}
{% endblock %}

{% block description %}
{% if terms %}
Search results for &ldquo;{{ terms }}&rdquo; on CaveDB.
{% else %}
Search for caves and cave systems on CaveDB.
{% endif %}
{% endblock %}

{% block content %}
{% if error %}
<!-- Error message -->
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

<!-- Header start -->
<h1 class="mb-0 display-4"><span class="text-muted">Search{% if terms %}:{% endif %}</span>{% if terms %} {{ terms }}{% endif %}</h1>
<span class="fw-light mt-0 text-muted">{{ number_of_results }} results on CaveDB</span>
<br /><br />
<!-- Header end -->

{% if results %}
<!-- Results table start -->
<div class="table-responsive">
  <table id="resultsList" class="table text-center">
    <thead>
      <tr>
        <th scope="col" class="text-center" colspan="10">Search results for &ldquo;{{ terms }}&rdquo;</th>
      </tr>

      <tr data-sort-method="thead">
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col">Region</th>
        <th scope="col">Location</th>
        <th scope="col" data-sort-method="number">Length (km)</th>
        <th scope="col" data-sort-method="number">Depth (m)</th>
        <th scope="col">Organisation</th>
        <th scope="col">Website</th>
        <th scope="col">Wikipedia</th>
      </tr>
    </thead>

    <tbody>

      {% for cave in results %}
      <tr>

        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-muted" href="{{ cave.url }}">{{ cave.name }}</a></td>
        <td>{{ cave.type }}</td>
        <td class="text-muted">
          <a href="{% url 'db:country' cave.country.slug %}" class="text-muted">{{ cave.country.name }}</a> /
          <a href="{% url 'db:region' cave.region.slug %}" class="text-muted">{{ cave.region.name }}</a>
        </td>
        <td><a href="{% url 'db:search' %}?terms={{ cave.location|urlencode }}" class="text-muted">{{ cave.location }}</a></td>
        <td>{{ cave.length|floatformat:"-3"|default:"-" }}</td>
        <td>{{ cave.depth|floatformat:"-3"|default:"-" }}</td>

        {% if cave.organisation.website %}
        <td>{{ cave.organisation.abbreviation }} <a class="text-muted" href="{{ cave.organisation.website }}"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>
        {% else %}
        <td>{{ cave.organisation.abbreviation|default:"-" }}</td>
        {% endif %}

        {% if cave.website %}
        <td><a href="{{ cave.website }}" class="text-muted"><i class="fa-solid fa-link"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

        {% if cave.wikipedia %}
        <td><a href="{{ cave.wikipedia }}" class="text-muted"><i class="fa-brands fa-wikipedia-w"></i></a></td>
        {% else %}
        <td>-</td>
        {% endif %}

      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
<!-- Results table end -->
{% else %}

<p class="lead">I'm sorry, there were no results for the specified query.</p>

{% endif %}
{% endblock %}

{% block footer_scripts %}
{% if results %}
<!-- Enable tablesort -->
<script>
  new Tablesort(document.getElementById('resultsList'));
</script>
{% endif %}
{% endblock %}

app/templates/navbar.html
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom mb-3" aria-label="navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'db:index' %}">CaveDB</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav me-auto">

          {% comment %}
          {% url 'db:index' as current_page %}
          <li class="nav-item">
            <a class="nav-link{% if request.get_full_path == current_page %} active{% endif %}" aria-current="page" href="{% url 'db:index' %}">Region List</a>
          </li>
          {% endcomment %}

        </ul>
        <form class="d-flex" name="search" method="GET" action="{% url 'db:search' %}">
          <input class="form-control me-2" type="search" placeholder="Caves and Systems" name="terms" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>